name: caddyshack

on:
  push:
    branches:
      - "master"
  workflow_dispatch: {}

env:
  VERS_TAG: ghcr.io/curtislarson/caddyshack:2.6.1-caddy-docker-proxy
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  caddyshack-docker-proxy:
    name: Build and Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: I'm alright
        uses: docker/setup-qemu-action@v2

      - name: Don't nobody worry 'bout me
        uses: docker/setup-buildx-action@v2

      - name: You got to gimme a fight
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Kenny Logginsto GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Kenny Logginsto DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: You got to gimme a fight
        uses: docker/build-push-action@v3
        with:
          context: ./caddy-docker-proxy
          push: true
          tags: ${{ env.VERS_TAG }}
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Why don't you just let me be?
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
