name: caddyshack

on:
  push:
    branches:
      - "master"
  workflow_dispatch: {}

env:
  VERS_TAG: ghcr.io/curtislarson/caddyshack:2.6.1-caddy-docker-proxy
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  caddyshack-docker-proxy:
    name: Build and Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Im all right
        uses: docker/setup-qemu-action@v2

      - name: Kenny Logginsto DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Kenny Logginsto GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Dont nobody worry bout me
        uses: docker/setup-buildx-action@v2

      - name: So I got that goin for me
        uses: docker/build-push-action@v3
        with:
          context: ./caddy-docker-proxy
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ env.VERS_TAG }}
          push: true
