name: esm

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/esm.yml"
      - "esm/**"
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: curtislarson/caddyshack/esm-sh
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  esm:
    name: Build and Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: I'm alright
        uses: docker/setup-qemu-action@v2

      - name: Don't nobody worry 'bout me
        uses: docker/setup-buildx-action@v2

      - name: Kenny Logginsto GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Kenny Logginsto DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Why don't you just let me be?
        uses: docker/build-push-action@v3
        with:
          context: ./esm
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
