name: esm

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/esm.yml"
      - "esm/**"
  workflow_dispatch: {}

env:
  IMAGE_NAME: ghcr.io/curtislarson/esm-sh
  PLATFORMS: linux/amd64,linux/arm64
  VERS_TAG: v104

jobs:
  esm:
    name: Build and Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Kenny Logginsto GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Kenny Logginsto DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Why don't you just let me be?
        uses: docker/build-push-action@v3
        with:
          context: ./esm
          push: true
          tags: ${{ env.IMAGE_NAME}}:${{ env.VERS_TAG }},${{ env.IMAGE_NAME}}:latest
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
